Improve jiri logging
Added warning level and formatting. Also all the messages should be
logged in one call instead of dividing them and logging them in seperate
calls. The general logging would be like

Error: Main error messages
Supporting content

Change-Id: I8f5b81930643e625336c91c4801904394da92d76